version: '3'

services:

    dinner_hall:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            -   "56565:56565"
        restart: unless-stopped
        networks:
            -   restaurant

networks:
    restaurant:
