version: '3'

services:

    kitchen:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            -   "56566:56566"
        restart: unless-stopped
        networks:
            -   restaurant

networks:
    restaurant:
